version: '3'

services:
  # app:
  #   build: .
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_DB: ${DATABASE_DB}
  #   depends_on:
  #     - db
  #   networks:
  #     - net
  db:
    restart: always
    container_name: postgres
    image: postgres:9.6
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
